version: '2'

services:
    jenkins1:
        image: jenkins/jenkins
        ports: 
            - "8088:8080"
        volumes: 
            - jenkins_home:/var/jenkins_home    
           
volumes:
     jenkins_home:
            
